import Head from "next/head";
import { useEffect, useState } from "react";
import { baseURL, fetchAPI } from "../helpers/ApiInstance";
import { Banner } from "../Components/Banner";
import { Property } from "../Components/Property";
import { Flex, Spinner } from "@chakra-ui/react";
export default function Home() {
  const [propertyForSale, setPropertyForSale] = useState([]);
  const [propertyForRent, setPropertyForRent] = useState([]);
  const [isLoading, setisLoading] = useState(false);
  const getData = async () => {
    try {
      setisLoading(true);
      const responseForSale = await fetchAPI(
        `${baseURL}/properties/list?locationExternalIDs=5002&purpose=for-sale&hitsPerPage=6`
      );
      const dataForSale = await responseForSale.data.hits;
      setPropertyForSale(dataForSale);

      const responseForRent = await fetchAPI(
        `${baseURL}/properties/list?locationExternalIDs=5002&purpose=for-rent&hitsPerPage=6`
      );
      const dataForRent = await responseForRent.data.hits;
      setPropertyForRent(dataForRent);
      setisLoading(false);
    } catch (err) {
      setisLoading(false);
    }
  };

  useEffect(() => {
    console.log("effected");
    getData();
  }, []);
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body>
        <main>
          <Banner
            imageURl={
              "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQOzh5iHp1MNyPY7a9JXxct3osuZ1JX_-GyJw&usqp=CAU"
            }
            purpose={"RENT A HOME"}
            title1={"Rental Homes For"}
            title2={"Everyone!"}
            desc1={"Explore Apartments, Villas, Homes"}
            desc2={"and more..."}
            buttonText={"Explore Rating"}
            linkName={"/search/?purpose=for-rent"}
          />
          {isLoading ? (
            <Flex h="60vh" justifyContent="center" alignItems={"center"}>
              <Spinner color="blue.500" size={"xl"} speed="0.5s" />
            </Flex>
          ) : (
            <Flex flexWrap={"wrap"} justifyContent="center">
              {propertyForRent?.map((property) => (
                <Property property={property} key={property.id} />
              ))}
            </Flex>
          )}
          <Banner
            imageURl={
              "https://www.teahub.io/photos/full/240-2401352_interior-design-high-resolution.jpg"
            }
            purpose={"BUY A HOME"}
            title1={"Find, Buy & Own Your"}
            title2={"Dream Home"}
            desc1={"Explore Apartments, Villas, Homes"}
            desc2={"and more..."}
            buttonText={"Explore Buying"}
            linkName={"/search/?purpose=for-sale"}
          />
          {isLoading ? (
            <Flex h="60vh" justifyContent="center" alignItems={"center"}>
              <Spinner color="blue.500" size={"xl"} speed="0.5s" />
            </Flex>
          ) : (
            <Flex flexWrap={"wrap"} justifyContent="center">
              {propertyForSale?.map((property) => (
                <Property property={property} key={property.id} />
              ))}
            </Flex>
          )}
        </main>
      </body>
    </>
  );
}
